### ISSUE TITLE
Clustering_KMeans-Sentinel2.ipynb Query

### ISSUE THREAD

**Issue by CSteele97** [acgeospatial/Satellite_Imagery_Python#1]
Hi @acgeospatial thanks for this great repo! 

I have a question regarding your Clustering_KMeans-Sentinel2.ipynb notebook - do you have any code to run the same clustering algorithm on many images at once as a sort of loop?
I would like to perform this classification on multiple images and having another method than doing each one individually would greatly reduce my workload!

Many thanks,
Chloe

**Comment by acgeospatial** [comment]
Hi Chloe,
You could take my code turn it into a function that you just parse the image path into (and other variables - #classes? max iterations etc) and then loop over all your images in a for loop and call the function within that loop. Should work.
Andrew
